name: Greetings

on: push

jobs:
  commandtest:
    runs-on: ubuntu-latest
    steps:
    - name: create file
      run: |
        touch testfile | echo "refs #123456 commit message" > testfile  
    - name: create file
      run: |
        echo ::set-env name=TEST::$(grep -i -E "refs[]*[#]*[0-9]+" testfile) 
    - name: Shell Test
      run: |
        echo ${{ env.TEST }}
        if [ -z ${{ env.TEST }} ]; then
          echo "there's no ticket number"
        else
          echo "this is ticket number: ${{ env.TEST }}"
        fi
        
