name: Greetings

on: push

jobs:
  commandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Shell Test
      run: |
        touch testfile | echo "refs #123456 commit message" > testfile
        ticket_number=$(grep -Eo "[0-9]+" testfile)
        echo $ticket_number
        if [ -z $ticket_number ]; then
          echo "there's no ticket number"
        else
          echo "this is ticket number: ${ticket_number}"
        fi
        
