name: Greetings

on: push

jobs:
  commandtest:
    runs-on: ubuntu-latest
    steps:
    - name: create ticket number file
      run: |
        touch testfile | echo "refs #123456 commit message" > testfile  
    - name: find ticket number and register environment variables
      id: findnumber
      run: |
        grep -i -E "[0-9]+" testfile
    - name: check ticket number from file
      run: |
        echo ${{ steps.findnumber.outputs.result }}
        if [ -z ${{ steps.findnumber.outputs.result }} ]; then
          echo "there's no ticket number"
        else
          echo "this is ticket number: ${{ env.TEST }}"
        fi
        
