name: Greetings

on: push

jobs:
  commandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Shell Test
      run: |
        touch testfile
        echo "refs #123456 commit message" > testfile
        cat testfile
        ticket_number=$(grep -Eo "[0-9]+" testfile)
        echo $ticket_number
        
