name: actions-test
on: pull_request
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get PullRequest Info
        uses: actions/github-script@v6
        id: story_data
        with:
          script: |
            var story_data = {
              title: context.payload.pull_request,
              url: context.payload.pull_request._links.html.href
            }
            console.log(context.payload.pull_request)
            return story_data
      - name: Show PullRequest Info
        env:
          STORY_DATA: ${{ toJson(steps.story_data) }}
        run: echo "$STORY_DATA"
