name: pr merged trigger test

on:
  pull_request:
    types:
      - closed

jobs:
  pr-merged-trigger-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
