name: pr merged trigger test

on:
  pull_request:
    types:
      - closed

jobs:
  pr-merged-trigger-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          echo "REPOSITORY_NAME_WITHOUT_SLASHES=${GITHUB_REPOSITORY/\//.}" >> $GITHUB_ENV
          echo "BRANCH_NAME_WITHOUT_SLASHES=${github.head_ref//\//.}" >> $GITHUB_ENV
          echo "${{ github.head.ref }}"
