name: pr merged trigger test

on:
  push:
    branches:
      - master

jobs:
  pr-merged-trigger-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          echo "REPOSITORY_NAME_WITHOUT_SLASHES=${GITHUB_REPOSITORY/\//.}" >> $GITHUB_ENV
          echo "BRANCH_NAME_WITHOUT_SLASHES=${GITHUB_HEAD_REF//\//.}" >> $GITHUB_ENV
